Description:
  Dependencies for AWS::CodeArtifact::Repository Contract Tests

Parameters:
  CallerAccount:
    Type: String

Resources:
  DomainForContractTests:
    Type: AWS::CodeArtifact::Domain
    Properties:
      DomainName:
        Fn::Sub 'domain-contract-test-${CallerAccount}'


  UpstreamForContractTests:
    Type: AWS::CodeArtifact::Repository
    Properties:
      RepositoryName: "upstream-repo-contract-test"
      Description: "upstream repo description"
      DomainName:
        Fn::Sub 'domain-contract-test-${CallerAccount}'
      ExternalConnections:
        - public:npmjs
    DependsOn: DomainForContractTests

Outputs:
  ContractTestDomainName:
    Value: Fn::GetAtt DomainForContractTests.Name
    Export:
      Name: awscodeartifactrepositorycto1

  ContractTestUpstreamRepositoryName:
    Value: "upstream-repo-contract-test"
    Export:
      Name: awscodeartifactrepositorycto2
